version: '3'
services:
  app:
    build: .
    command: /sbin/init
    privileged: true
    hostname: app.local
    container_name: app
    volumes:
      - ./:/var/www/

  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="hoge"
