version: '3'
services:
  app:
    image: gamesrv:latest
    command: /sbin/init
    privileged: true
    hostname: all-in.local
    container_name: all-in

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "hoge"
