version: '3'
services:
  app:
    build: .
    command: /sbin/init
    privileged: true
    hostname: app.local
    container_name: app
    ports:
      - '3000:3030'
    volumes:
      - ./:/var/www/

    #command: bash -c "cd /var/www && bundle exec rails s"
        #command: /sbin/init

  db:
    image: mysql/mysql-server:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD="hoge"
